export default [
	{"LSAbbreviation":"aaa","x":"1","y":"0","irregular":false,"code":"aaa","name":"Enfield"},
	{"LSAbbreviation":"bbb","x":"2","y":"0","irregular":false,"code":"bbb","name":"Harrow"},
	{"LSAbbreviation":"ccc","x":"3","y":"0","irregular":false,"code":"ccc","name":"Barnet"},
	{"LSAbbreviation":"ddd","x":"1","y":"1","irregular":false,"code":"ddd","name":"Haringey"},
	{"LSAbbreviation":"eee","x":"2","y":"2","irregular":true,"code":"eee","name":"Waltham Forest"},
	{"LSAbbreviation":"fff","x":"3","y":"2","irregular":false,"code":"fff","name":"Hillingdon"},
	{"LSAbbreviation":"ggg","x":"4","y":"2","irregular":false,"code":"ggg","name":"Ealing"},
	{"LSAbbreviation":"hhh","x":"0","y":"3","irregular":false,"code":"hhh","name":"Brent"},
	{"LSAbbreviation":"iii","x":"1","y":"3","irregular":true,"code":"iii","name":"Camden"},
	{"LSAbbreviation":"jjj","x":"2","y":"3","irregular":true,"code":"jjj","name":"Islington"},
	{"LSAbbreviation":"kkk","x":"1","y":"4","irregular":false,"code":"kkk","name":"Hackney"},
	{"LSAbbreviation":"lll","x":"2","y":"4","irregular":false,"code":"lll","name":"Redbridge"},
	{"LSAbbreviation":"mmm","x":"3","y":"4","irregular":false,"code":"mmm","name":"Havering"},
  {"LSAbbreviation":"nnn","x":"2","y":"5","irregular":false,"code":"nnn","name":"Hounslow"}, 
];